export const searchList = [
  { title: 'Button 按钮', rule: 'buttonButton 按钮', url: 'button' },
  { title: 'Svg Icon 图标', rule: 'svg-iconSvgIcon图标', url: 'svg-icon', },
  { title: 'Link 链接', rule: 'linkLink链接', url: 'link' },
  { title: 'Text 文字', rule: 'textText文字', url: 'text' },
  { title: 'Layout 布局', rule: 'layoutLayout布局', url: 'layout' },
  { title: 'Space 间距', rule: 'spaceSpace间距', url: 'space' },
  { title: 'Color 色彩', rule: 'colorColor色彩', url: 'color' },
  { title: 'Badge 角标', rule: 'badgeBadge角标', url: 'badge' },
  { title: 'Image 图片', rule: 'imageImage图片', url: 'image' },
  { title: 'Image Preview 图片预览', rule: 'image-previewImagePreview图片预览', url: 'image-preview' },
  { title: 'Card 卡片', rule: 'cardCard卡片', url: 'card' },
  { title: 'Tag 标签', rule: 'tagTag标签', url: 'tag' },
  { title: 'Switch 开关', rule: 'switchSwitch开关', url: 'switch' },
  { title: 'Avatar 头像', rule: 'avatarAvatar头像', url: 'avatar' },
  { title: 'Progress 进度条', rule: 'progressProgress进度条', url: 'progress' },
  { title: 'Empty 空状态', rule: 'emptyEmpty空状态', url: 'empty' },
  { title: 'List 列表', rule: 'listList列表', url: 'list' },
  { title: 'Radio 单选框', rule: 'radioRadio单选框', url: 'radio' },
  { title: 'Checkbox 复选框', rule: 'checkboxCheckbox复选框', url: 'checkbox' },
  { title: 'ExpandCard 折叠动效', rule: 'expand-cardExpandCard折叠动效', url: 'expand-card' },
  { title: 'Tree 树', rule: 'treeTree树', url: 'tree' },
  { title: 'StickyCard 粘性卡片', rule: 'sticky-cardStickyCard粘性卡片', url: 'sticky-card' },
  { title: 'Rate 评分', rule: 'rateRate评分', url: 'rate' },
  { title: 'Input 输入框', rule: 'inputInput输入框', url: 'input' },
  { title: 'Up Load 文件上传', rule: 'up-loadUpLoad文件上传', url: 'up-load' },
  { title: 'Table 表格', rule: 'tableTable表格', url: 'table' },
  { title: 'Breadcrumb 面包屑', rule: 'breadcrumbBreadcrumb面包屑', url: 'breadcrumb' },
  { title: 'Page Header 页头', rule: 'page-headerPageHeader页头', url: 'page-header' },
  { title: 'Close Btn 关闭按钮', rule: 'close-btnCloseBtn关闭按钮', url: 'close-btn' },
  { title: 'Dropdown 下拉菜单', rule: 'dropdownDropdown下拉菜单', url: 'dropdown' },
  { title: 'Alert 警告', rule: 'alertAlert警告', url: 'alert' },
  { title: 'Loading 加载', rule: 'loadingLoading加载', url: 'loading' },
  { title: 'Message 消息提示', rule: 'messageMessage消息提示', url: 'message' },
  { title: 'Notification 通知', rule: 'notificationNotification通知', url: 'notification' },
  { title: 'Skeleton 骨架屏', rule: 'skeletonSkeleton骨架屏', url: 'skeleton' },
  { title: 'Loading Bar 加载条', rule: 'loading-barLoadingBar加载条', url: 'loading-bar' },
  { title: 'BackTop 返回顶部', rule: 'back-topBackTop返回顶部', url: 'back-top' },
  { title: 'Dialog 对话框', rule: 'dialogDialog对话框', url: 'dialog' },
  { title: 'Drawer 抽屉', rule: 'drawerDrawer抽屉', url: 'drawer' },
  { title: 'Tooltip 消息提示', rule: 'tooltipTooltip消息提示', url: 'tooltip' },
  { title: 'Popup 弹出窗口', rule: 'popupPopup弹出窗口', url: 'popup' },
  { title: 'Swap 切换', rule: 'swapSwap 切换', url: 'swap' },
  { title: 'Toolbar 工具栏', rule: 'toolbarToolbar工具栏', url: 'toolbar' },
  { title: 'Divider 分隔线', rule: 'dividerDivider分隔线', url: 'divider' },
  { title: 'Watermark 水印', rule: 'watermarkWatermark水印', url: 'watermark' },
  { title: 'Ripple 涟漪', rule: 'rippleRipple涟漪', url: 'ripple' },
  { title: 'Calendar 日历', rule: 'calendarCalendar日历', url: 'calendar' }
] as const
