declare module 'vue' {
  export interface GlobalComponents {
    FButton: typeof import('./button/src/button.vue')
    FButtonGroup: typeof import('./button-group/src/button-group.vue')
    FIcon: typeof import('./icon/src/icon.vue')
    FLink: typeof import('./link/src/link.vue')
    FImage: typeof import('./image/src/image.vue')
    FCard: typeof import('./card/src/card.vue')
    FTag: typeof import('./tag/src/tag.vue')
    FDivider: typeof import('./divider/src/divider.vue')
    FFooter: typeof import('./footer/src/footer.vue')
    FHeader: typeof import('./header/src/header.vue')
    FAside: typeof import('./aside/src/aside.vue')
    FMain: typeof import('./main/src/main.vue')
    FLayout: typeof import('./layout/src/layout.vue')
    FSwitch: typeof import('./switch/src/switch.vue')
    FBadge: typeof import('./badge/src/badge.vue')
    FAvatar: typeof import('./avatar/src/avatar.vue')
    FBackTop: typeof import('./back-top/src/back-top.vue')
    FBreadcrumb: typeof import('./breadcrumb/src/breadcrumb.vue')
    FText: typeof import('./text/src/text.vue')
    FLoading: typeof import('./loading/src/loading.vue')
    FProgress: typeof import('./progress/src/progress.vue')
    FSpace: typeof import('./space/src/space.vue')
    FDialog: typeof import('./dialog/src/dialog.vue')
    FTooltip: typeof import('./tooltip/src/tooltip.vue')
    FDrawer: typeof import('./drawer/src/drawer.vue')
    FPageHeader: typeof import('./page-header/src/page-header.vue')
    FAlert: typeof import('./alert/src/alert.vue')
    FList: typeof import('./list/src/list.vue')
    FToolbar: typeof import('./toolbar/src/toolbar.vue')
    FToolbarItem: typeof import('./toolbar-item/src/toolbar-item.vue')
    FWatermark: typeof import('./watermark/src/watermark.vue')
  }
}

export {}
