export { install, installFn } from './install'
export { loadImage } from './load-image'
export { keepDecimal, debounce, isString, isNumber, pastTime } from './utils'
export { Ripples } from './ripples'
export { ChangeColor } from './change-color'
export { createBase64 } from './watermark'
