# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.234.0/containers/typescript-node/.devcontainer/base.Dockerfile

# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
ARG VARIANT="18-bullseye"
FROM mcr.microsoft.com/vscode/devcontainers/typescript-node:0-${VARIANT}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install an additional version of node using nvm
# ARG EXTRA_NODE_VERSION=10
# RUN su node -c "source /usr/local/share/nvm/nvm.sh && nvm install ${EXTRA_NODE_VERSION}"

# [Optional] Uncomment if you want to install more global node packages
USER node
#安装starship美化
RUN curl -o /tmp/starship.sh -sS https://starship.rs/install.sh && sh /tmp/starship.sh --yes && echo 'eval "$(starship init bash)"'>> /home/node/.bashrc
#安装pnpm并设置初始化环境变量
RUN npm install -g pnpm
ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PATH=${PNPM_HOME}:${PATH}
#安装常用工具包
RUN pnpm add -g tsx rimraf


