export { install } from './install'
export { loadImage } from './loadImage'
export { keepDecimal, debounce } from './utils'
export { Ripples } from './ripples'
export { ChangeColor } from './changeColor'
